[colors.bright]
black = "0x777777"
blue = "0xb3d1ff"
cyan = "0x79e0ed"
green = "0x9ddeaf"
magenta = "0xfabdf0"
red = "0xffbbb2"
white = "0xffffff"
yellow = "0xe0ce91"

[colors.normal]
black = "0x4e4e4e"
blue = "0x5879af"
cyan = "0x008592"
green = "0x468459"
magenta = "0x9c6594"
red = "0xa9635d"
white = "0xcfcfcf"
yellow = "0x84763d"

[colors.primary]
background = "0x292929"
foreground = "0xa2a2a2"
