#!/bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
$XDG_CONFIG_HOME/polybar/launch.sh &
feh --no-fehbg --bg-fill '/home/shmcg/.config/wallpaper/upper_crosstich_dracula.png'
dunst &

# Define Desktops

bspc monitor DP-1 -d MAIN HACK DEV MONO
bspc monitor DP-2 -d ALT EML CHAT MEDIA

# Global Settings

# Theme Settings - Dracula
bspc config normal_border_color "#44475a"
# active node is the focused one on an unfocused monitor
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#bd93f9"
bspc config urgent_border_color "#ff5555"
bspc config presel_feedback_color "#44475a"
bspc config presel_feedback true
bspc config split_ratio          0.52


#bspc config top_padding 30 # leave room for polybar
#bspc config bottom_padding 0
#bspc config left_padding 0
#bspc config right_padding 0
bspc config window_gap 8
bspc config border_width 3

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc desktop 'MONO' --layout monocle
# Rules

# Clear existing rules on reload
bspc rule --remove *
bspc rule -a Emacs state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
