#!/bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
feh --no-fehbg --bg-fill '/home/shmcg/.config/wallpaper/upper_crosstich_dracula.png'
dunst &

# Define Desktops
desktop_list_01="MAIN HACK DEV MONO"
desktop_list_02="ALT EML CHAT MEDIA"
desktop_list_03="IX X XI XII"
desktop_list_all="$desktop_list_01 $desktop_list_02"
#bspc monitor DP-1 -d MAIN HACK DEV MONO
#bspc monitor DP-2 -d ALT EML CHAT MEDIA

if type "xrandr"; then
	monitor_count=$(xrandr --query | grep -w "connected" | wc -l)
	monitor_list=$(xrandr --query | grep -w "connected" | cut -d" " -f1)
	monitor_primary=$(xrandr --query | grep -w "primary" | cut -d" " -f1)
	if [ $monitor_count -eq 1 ]; then
		bspc monitor $monitor_list -d $desktop_list_all
	else
		for m in $(echo $monitor_list)
		do
			echo $m
		done
	fi
else
	bspc monitor $monitor_list -d $desktop_list_all
fi

# Global Settings

# Theme Settings - Dracula
bspc config normal_border_color "#44475a"
# active node is the focused one on an unfocused monitor
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#bd93f9"
bspc config urgent_border_color "#ff5555"
bspc config presel_feedback_color "#44475a"
bspc config presel_feedback true
bspc config split_ratio          0.52


#bspc config top_padding 30 # leave room for polybar
#bspc config bottom_padding 0
#bspc config left_padding 0
#bspc config right_padding 0
bspc config window_gap 8
bspc config border_width 3

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc desktop 'MONO' --layout monocle
# Rules

# Clear existing rules on reload
bspc rule --remove *
bspc rule -a Emacs state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
