[general]
# Start Satty in fullscreen mode
fullscreen = false
# Exit directly after copy/save action
early-exit = false
# Draw corners of rectangles round if the value is greater than 0 (0 disables rounded corners)
corner-roundness = 0
# Select the tool on startup [possible values: pointer, crop, line, arrow, rectangle, text, marker, blur, brush]
initial-tool = "brush"
# Configure the command to be called on copy, for example `wl-copy`
copy-command = "wl-copy"
# Increase or decrease the size of the annotations
annotation-size-factor = 2
# Filename to use for saving action. Omit to disable saving to file. Might contain format specifiers: https://docs.rs/chrono/latest/chrono/format/strftime/index.html
# https://github.com/gabm/Satty/issues/285 0.20.0 will support ~
#output-filename = "/tmp/test-%Y-%m-%d_%H:%M:%S.png"
# After copying the screenshot, save it to a file as well
save-after-copy = false
# Hide toolbars by default
#default-hide-toolbars = false
# Experimental: whether window focus shows/hides toolbars. This does not affect initial state of toolbars, see default-hide-toolbars.
#focus-toggles-toolbars = false
# Fill shapes by default
#default-fill-shapes = false
# The primary highlighter to use, the other is accessible by holding CTRL at the start of a highlight [possible values: block, freehand]
primary-highlighter = "block"
# Disable notifications
disable-notifications = false
# Actions to trigger on right click (order is important)
# [possible values: save-to-clipboard, save-to-file, exit]
actions-on-right-click = []
# Actions to trigger on Enter key (order is important)
# [possible values: save-to-clipboard, save-to-file, exit]
actions-on-enter = ["save-to-clipboard"]
# Actions to trigger on Escape key (order is important)
# [possible values: save-to-clipboard, save-to-file, exit]
actions-on-escape = ["exit"]
# request no window decoration. Please note that the compositor has the final say in this. At this point. requires xdg-decoration-unstable-v1.
no-window-decoration = true
# experimental feature: adjust history size for brush input smoothing (0: disabled, default: 0, try e.g. 5 or 10)
brush-smooth-history-size = 0

# Tool selection keyboard shortcuts
#[keybinds]
#pointer = "p"
#crop = "c"
#brush = "b"
#line = "l"
#arrow = "a"
#rectangle = "r"
#ellipse = "e"
#text = "t"
#marker = "m"
#blur = "o"
#highlight = "h"

# Font to use for text annotations
[font]
family = "Roboto"
style = "Regular"

# Custom colours for the colour palette
[color-palette]
# These will be shown in the toolbar for quick selection
palette = [
    "#f1ff5e",
    "#5eff6c",
    "#5ea1ff",
    "#bd5eff",
    "#ff5ef1",
]
custom = [
    "#ff6e5e",
	"#ffbd5e",
    "#f1ff5e",
    "#5eff6c",
    "#5ef1ff",
    "#5ea1ff",
    "#bd5eff",
    "#ff5ef1",
    "#ff5ea0",
    "#000000",
    "#16181a",
    "#1e2124",
    "#3c4048",
    "#7b8496",
    "#ffffff",
]
