#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "OpenBSD" {
	set root=(hd1,1)
	chainloader +1
}

menuentry "OpenBSD 7.0" {
	insmod gzio
	insmod zfs
	insmod part_gpt
	search --no-floppy --fs-uuid --set=root FA99-170A
	kopenbsd /bsd -r sd0a
}

menuentry "Restart System" {
	echo "System rebooting..."
	reboot
}

menuentry "Shutdown System" {
	echo "System shutting down..."
	halt
}
