#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "OpenBSD" {
	insmod fat
	search --no-floppy --fs-uuid --set=root FA99-170A
	chainloader (hd1,gpt1)/efi/boot/bootx64.efi
}

menuentry "Restart System" {
	echo "System rebooting..."
	reboot
}

menuentry "Shutdown System" {
	echo "System shutting down..."
	halt
}
