#New-Item -ItemType SymbolicLink -Path "$HOME\" -Target "$HOME\dotfiles"
New-Item -ItemType SymbolicLink -Path "$HOME\.gvimrc" -Target "$HOME\dotfiles\vim\.gvimrc"
New-Item -ItemType SymbolicLink -Path "$HOME\.scripts" -Target "$HOME\dotfiles\scripts\.scripts"
New-Item -ItemType SymbolicLink -Path "$HOME\.vim" -Target "$HOME\dotfiles\vim\.vim\"
New-Item -ItemType SymbolicLink -Path "$HOME\.vimrc" -Target "$HOME\dotfiles\vim\.vimrc"
New-Item -ItemType SymbolicLink -Path "$HOME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\shm-keybinds.ahk.lnk" -Target "$HOME\dotfiles\auto-hotkey\shm-keybinds.ahk"
New-Item -ItemType SymbolicLink -Path "$HOME\reference" -Target "$HOME\dotfiles\reference\reference"
New-Item -ItemType SymbolicLink -Path "$HOME\shm-keybinds.ahk" -Target "$HOME\dotfiles\auto-hotkey\shm-keybinds.ahk"